FROM postgres:15

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        build-essential \
        postgresql-server-dev-15 \
        ca-certificates && \
    cd /tmp && \
    git clone --depth 1 --branch v1.6.4 https://github.com/citusdata/pg_cron.git && \
    cd pg_cron && \
    make && \
    make install && \
    cd / && \
    rm -rf /tmp/pg_cron && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER postgres
